### ISSUE TITLE
Time For a New Release

### ISSUE THREAD

**Issue by seanmalloy** [chef-partners/gcewinpass#6]
Would it be possible to bump the version and release a new version to rubygems.org?

I'm willing to do the code updates if needed to bump the version.

**Comment by seanmalloy** [comment]
@adamleff what are your thoughts on this?

**Comment by adamleff** [comment]
@seanmalloy after I merged in #2 and #5, I bumped the version to 1.1.0 and released a new version to Rubygems early this morning. You should be good, yes?

**Comment by seanmalloy** [comment]
@adamleff I did not see that. Yes that is all I needed. Sorry for the noise.

**Comment by adamleff** [comment]
No apologies needed! I’m just glad someone gets used out of this 🙂
